version: '3.4'

services:
  php:
    image: teltek/pumukit:4.x
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
      cache_from:
        - teltek/pumukit
        - teltek/nginx
    depends_on:
      - db
    volumes:
      # Comment out the next lines in production
      # - ./web/storage:/srv/pumukit/web/storage:rw,cached
      # - ./web/uploads:/srv/pumukit/web/uploads:rw,cached
      # Comment out the next line for dev
      - ./:/srv/pumukit

  h2-proxy:
    image: teltek/nginx:4.x
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./doc/docker/nginx
      cache_from:
        - teltek/pumukit
        - teltek/nginx
    depends_on:
      - php
    volumes:
      # Comment out the next lines in production
      # - ./web/storage:/srv/pumukit/web/storage:ro
      # - ./web/uploads:/srv/pumukit/web/uploads:ro
      # - ./web/bundles:/srv/pumukit/web/bundles:ro
      # Comment out the next line for dev
      - ./:/srv/pumukit
      - /etc/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - /var/www/certbot/:/var/www/certbot/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - /var/www/certbot/:/var/www/certbot/:rw
      - /etc/letsencrypt/:/etc/letsencrypt/:rw

  db:
    image: mongo:4.0
    restart: unless-stopped
    volumes:
      - db-data:/data/db:rw

  redis:
    image: redis
    restart: unless-stopped
    env_file:
      - .env

volumes:
  db-data: {}

